openshift/bpfman-operator

- Containerfile.bpfman-agent.openshift
- Containerfile.bpfman-operator.openshift
Non-linear parsing of case-insensitive content in golang.org/x/net/html
> build crictl from source to fix CVE-2024-45338

- .tekton/ocp-bpfman-operator-catalog-ocp4-19-pull-request.yaml
- .tekton/ocp-bpfman-operator-catalog-ocp4-19-push.yaml
- rpms.lock.yaml
```sh
Results:
✕ [Violation] rpm_repos.ids_known
ImageRef: quay.io/redhat-user-workloads/ocp-bpfman-tenant/ocp-bpfman-operator-catalog-ocp4-19@sha256:445cf6918ff9643fa39cab6fca7db0a3ee153361232a3da30c2198748c13d237
Reason: RPM repo id check failed: An RPM component in the SBOM specified an unknown or disallowed repository_id:
pkg:rpm/redhat/python3-ruamel-yaml@0.16.6-7.el9.1?arch=x86_64&checksum=sha256:edfa4be465a7ce774309cf67c85bd1a2f42fb9b5fe2508ccf681605c2ff21ee9&repository_id=codeready-builder-for-ubi-9-x86_64
Title: All rpms have known repo ids
Description: Each RPM package listed in an SBOM must specify the repository id that it comes from, and that repository id must
be present in the list of known and permitted repository ids. Currently this is rule enforced only for SBOM …
```
> Add fips check to fbc pipeline and fix violation with one of the used repos

- .tekton/multi-arch-build-pipeline.yaml
- .tekton/single-arch-build-pipeline.yaml
Add new `sast-shell-check` to konflux pipelines
the defintion of this new task was added by NOO via https://github.com/netobserv/network-observability-operator/pull/1378
note: bpfman tekton and NOO are different layout so we just picked up the task defintion and applied them to the where bpfman tasks are defined
> Add new sast-shell-check task

- Containerfile.bpfman-agent.openshift
- Containerfile.bpfman-operator.openshift
Set `CGO_ENABLED=1` and enable the `strictfipsruntime` experiment for OpenShift container builds of `bpfman-agent` and `bpfman-operator`.
This ensures compliance with FIPS requirements.
> Enable CGO and strict FIPS runtime in OpenShift builds

- go.mod
- go.sum
- vendor/github.com/emicklei/go-restful/v3/CHANGES.md
- vendor/github.com/emicklei/go-restful/v3/README.md
- vendor/github.com/emicklei/go-restful/v3/jsr311.go
- vendor/github.com/emicklei/go-restful/v3/route.go
- vendor/modules.txt
This PR replaces https://github.com/openshift/bpfman-operator/pull/406, which encountered merge conflicts and vendor inconsistencies due to the original PR transitioning from v3.12.0 to v3.12.2 and other upstream go module changes.
Steps: 
```
go get github.com/emicklei/go-restful/v3@v3.12.2
go mod tidy
go mod vendor
```
> chore(deps): update module github.com/emicklei/go-restful/v3 to v3.12.2

- .tekton/ocp-bpfman-operator-catalog-ocp4-19-pull-request.yaml
- .tekton/ocp-bpfman-operator-catalog-ocp4-19-push.yaml
- .tekton/ocp-bpfman-operator-catalog-ocp4-20-pull-request.yaml
- .tekton/ocp-bpfman-operator-catalog-ocp4-20-push.yaml
The current FBC catalog pipelines for OCP 4.19 and 4.20 are missing the required `fbc-target-index-pruning-check` task, which is causing Konflux validation errors. This commit adds the missing task to all four pipeline files (pull request and push variants for both versions).
The task has been placed right after the validate-fbc task with the same conditional logic, targeting the standard registry index at registry.redhat.io/redhat/redhat-operator-index. I took a minimal approach, adding only what's needed without changing the existing pipeline structure.
> fix: add fbc-target-index-pruning-check task to FBC pipelines

- catalog/index.yaml
- hack/update_fbc.sh
Rebuild the catalog/index.yaml to drop kube-rbac-proxy[1] references. Update the hack/update_fbc.sh script so that we reference konflux-built images and not upstream image references.
The image was selected from[2] and the catalog was updated by running:
make BUNDLE_IMG=quay.io/redhat-user-workloads/ocp-bpfman-tenant/ocp-bpfman-operator-bundle@sha256:7f701331ca76d520f9b7ea68a17259b9e5f5ac5fd9ca97fa4b13fd7159ece8fd catalog-update`
The hack/update_fbc.sh script also
[1] https://github.com/openshift/bpfman-operator/pull/444
[2] https://catalog.redhat.com/software/containers/bpfman/bpfman-operator-bundle/66d860e5ca5808a4be0c6c8a
> catalog/index.yaml: drop kube-rbac-proxy relatedImages references

- go.mod
Simplify Go version specification in go.mod to use canonical Go 1.23
format and remove explicit toolchain directive.
> go.mod: Switch to Go 1.23

- .tekton/multi-arch-build-pipeline.yaml
- .tekton/ocp-bpfman-operator-catalog-ocp4-18-pull-request.yaml
- .tekton/ocp-bpfman-operator-catalog-ocp4-18-push.yaml
- .tekton/ocp-bpfman-operator-catalog-ocp4-19-pull-request.yaml
- .tekton/ocp-bpfman-operator-catalog-ocp4-19-push.yaml
- .tekton/ocp-bpfman-operator-catalog-ocp4-20-pull-request.yaml
- .tekton/ocp-bpfman-operator-catalog-ocp4-20-push.yaml
- .tekton/ocp-bpfman-operator-catalog-pull-request.yaml
- .tekton/ocp-bpfman-operator-catalog-push.yaml
Add IMAGE_URL and IMAGE_DIGEST parameters to all apply-tags tasks in
Tekton pipelines to resolve validation failures.
https://github.com/openshift/bpfman-operator/pull/558 bumps the
apply-tags parameters requirements. And catalogue builds have been
failing for more than a week.
https://issues.redhat.com/browse/KFLUXSPRT-3675
> Fix apply-tags pipeline validation errors

- Makefile
- bundle/metadata/dependencies.yaml
This is a cherry-pick of https://github.com/bpfman/bpfman-operator/pull/373.
After deploying the selinux profile, the status on the Selinux Profile
is “Pending”. security-profiles-operator is currently deployed in
OpenShift by making it a dependency of bpfman-operator. As a result, the
security-profiles-operator is deployed in the bpfman namespace.
security-profiles-operator encounters issues with this because there are
other daemonsets in the namespace. Short term, remove the dependency.
security-profiles-operator is still required, it just won't be
auto-installed.
Related: #331
Related: https://github.com/kubernetes-sigs/security-profiles-operator/issues/2699
Signed-off-by: Billy McFall <22157057+Billy99@users.noreply.github.com>
> remove dependency on security-profiles-operator

- hack/patch_catalog_build_date.py
- hack/update_catalog.sh
The catalog's createdAt field was previously static, showing an
outdated date in the OpenShift console. This change ensures the
catalog reflects when it was actually built.
Changes:
- Add patch_catalog_release_date.py script to update catalog timestamps
- Modify update_catalog.sh to call the new timestamp update script
The catalog's createdAt date now updates dynamically during the build
process, providing users with accurate information about catalog
freshness in the OpenShift console.
> Update catalog build process to set createdAt timestamp

- .tekton/multi-arch-build-pipeline.yaml
- .tekton/single-arch-build-pipeline.yaml
Add required image-digest parameter to sast-unicode-check task in both
multi-arch and single-arch build pipelines. The parameter became
required in version 0.3 with no default value.
Fixes pipeline failures with error: "missing values for these params
which have no default values: [image-digest]"
Reference: https://github.com/konflux-ci/build-definitions/blob/main/task/sast-unicode-check-oci-ta/0.3/MIGRATION.md
Should fix https://github.com/openshift/bpfman-operator/pull/611.
> Fix sast-unicode-check-oci-ta v0.3 missing image-digest parameter

- .tekton/ocp-bpfman-agent-pull-request.yaml
- .tekton/ocp-bpfman-agent-push.yaml
- .tekton/ocp-bpfman-operator-bundle-pull-request.yaml
- .tekton/ocp-bpfman-operator-bundle-push.yaml
- .tekton/ocp-bpfman-operator-pull-request.yaml
- .tekton/ocp-bpfman-operator-push.yaml
This reverts commit 5b76489d8e8823fe05afbce37a62c77f2a97b13c.
The change 5b76489d8e8823fe05afbce37a62c77f2a97b13c meant that the konflux jobs stopped running. 
Revert this change whilst we work out why the release of the bpfman-operator "application" fails. This is clearly the wrong change.
> Revert "Add hermetic parameter to operator, agent, and bundle pipelines"

- hack/update_bundle.sh
The `fbc-fips-check-oci-ta` task is failing during enterprise contract validation with this error:
```
Error: Unable to scan image: Could not get com.redhat.component label for quay.io/bpfman/bpfman-operator:latest
```
**Full task log:**
```
step-fips-operator-check-step-action :-
Related images are :
quay.io/bpfman/bpfman-operator:latest
Target OCP version found: -V=4.19
Image Mirror Map found:
{
"registry.redhat.io/bpfman/bpfman-agent": [
"quay.io/redhat-user-workloads/ocp-bpfman-tenant/ocp-bpfman-agent"
],
"registry.redhat.io/bpfman/bpfman-operator-bundle": [
"quay.io/redhat-user-workloads/ocp-bpfman-tenant/ocp-bpfman-operator-bundle"
],
"registry.redhat.io/bpfman/bpfman-rhel9-operator": [
"quay.io/redhat-user-workloads/ocp-bpfman-tenant/ocp-bpfman-operator"
], …
```
> Fix fbc-fips-check-oci-ta task failure by ensuring comprehensive upstream image replacement

- .tekton/multi-arch-build-pipeline.yaml
- .tekton/single-arch-build-pipeline.yaml
PR #655 updated some buildah tasks but missed `ecosystem-cert-preflight-checks`, which was causing Enterprise Contract validation failures in downstream releases.
- Updated `task-ecosystem-cert-preflight-checks` SHA256 from `f99d2bdb02f13223...` to `fd146c14794b6bc15384359...`
- Applied the update to both multi-arch and single-arch build pipelines
- `test.no_failed_informative_tests` warnings in Enterprise Contract validation
- `CouldntGetTask` errors preventing successful builds
- `test.no_erred_tests` and related pipeline failures
The automated dependency update bot appears to have missed this task reference when it updated other Konflux Tekton tasks. This completes the incomplete updates from PR #655.
The new SHA256 hash corresponds to the latest trusted version as reported by …
> Complete Tekton task updates missed by PR #655

- .tekton/multi-arch-build-pipeline.yaml
- .tekton/single-arch-build-pipeline.yaml
• Updates ecosystem-cert-preflight-checks task to use trusted SHA version
• Resolves trust violations affecting all build pipelines 
• Changes applied to both multi-arch and single-arch build configurations
> Fix ecosystem-cert-preflight-checks task trust violations

- .tekton/ocp-bpfman-operator-push.yaml
- hack/update_bundle_python.py
Fix Konflux component update automation to keep both bundle scripts synchronised with the latest operator images, and resolve a critical bug in the Python bundle script that prevented operator image replacements.
The bundle build process uses two scripts to patch CSV files with downstream operator images:
- `hack/update_bundle.sh` (used by shell-based builds)  
- `hack/update_bundle_python.py` (used by `Containerfile.bundle.openshift`)
However, Konflux component updates were only nudging `update_bundle.sh`, causing the scripts to drift badly out of sync:
- `hack/update_bundle.sh`: `sha256:84314fd013ff` (30 July 2025, current)
- `hack/update_bundle_python.py`: `sha256:fd530e80207d` (so old it no longer exists in registry)
Additionally, the Python script had a critical bug where it used …
> Fix Konflux nudging and bundle script synchronisation

- Containerfile.catalog.openshift-4.17
- Containerfile.catalog.openshift-4.18
- Containerfile.catalog.openshift-4.19
- Containerfile.catalog.openshift-4.20
- hack/update_catalog.sh
This PR replaces Python-based catalog processing with shell-based sed operations to achieve FIPS compliance whilst maintaining compatibility with the nudging workflow.
**Key improvements:**
- Eliminates Python dependencies during catalog builds for FIPS compliance
- Maintains nudging workflow compatibility by preserving export variable structure
- Processes catalog files directly avoiding unnecessary file copying
- Adds comprehensive before/after logging for transparency
- Updates Containerfile comments to explain USER root requirement
**Technical implementation:**
- Uses sed with extended regex to replace image references in catalog YAML
- Replaces upstream quay.io/bpfman/bpfman-operator:latest with downstream SHA references
- Updates bundle image references to current nudged versions
- …
> Replace Python catalog processing with shell-based FIPS-compliant solution

- catalog/index.yaml
Updates catalog to reference operator images published in releases:
- bpfman-ocp4.19-r4dn7-20250804 ✅ Succeeded  
- bpfman-operator-ocp4.19-r4dn7-20250804 ✅ Succeeded
**Images now available in registry.redhat.io/bpfman/\*:**
- bpfman-rhel9-operator@sha256:7a3c4e3bf315ee004833cbbd4e8847b5520afb056fecbe8019528d1f7ef4abf8
- bpfman-operator-bundle@sha256:36922ea0b333bf60bfd358425681c472db07a99dd07c929383ee3bcc5e93c19f
**Verification:**
This completes the operator-first stage of the BPFman 4.19 release workflow.
> Update catalog to use published operator images

- .tekton/ocp-bpfman-operator-catalog-ocp4-19-pull-request.yaml
- .tekton/ocp-bpfman-operator-catalog-ocp4-19-push.yaml
Skip the fbc-target-index-pruning-check task in OCP 4.19 catalog pipelines.
The fbc-target-index-pruning-check task fails because our catalog generation process doesn't manage multiple releases/versions properly. Since BPFman is in Tech Preview, our catalog contains only the current release, effectively pruning all previous versions from the target index (registry.redhat.io/redhat/redhat-operator-index). 
This triggers validation failures as the task detects entire channels being removed from the catalog.
As a Tech Preview project, this catalog pruning behaviour is acceptable. Modified the when condition to always skip this validation task for OCP 4.19 catalog builds while preserving all other validation tasks (validate-fbc, fbc-fips-check-oci-ta, etc.).
- …
> Skip fbc-target-index-pruning-check task in OCP 4.19 catalog pipelines

- Containerfile.bpfman-operator.openshift
BPFman operator panics on OpenShift when deployed via OperatorHub. The controller crashes trying to load `./config/bpfman-deployment/metrics-proxy-daemonset.yaml` which doesn't exist in the container.
When metrics proxy support was added in 63cde58a, the regular Containerfile was updated to copy the new config file but the OpenShift-specific Containerfile was missed. This means:
- Upstream builds work fine
- OpenShift builds are missing the file
- Runtime panic when controller tries to load it
Add the missing COPY line to the OpenShift Containerfile to match what's already in the regular one.
> Fix missing metrics-proxy-daemonset.yaml in OpenShift Containerfile

- .tekton/bpfman-agent-ystream-pull-request.yaml
- .tekton/bpfman-agent-ystream-push.yaml
- .tekton/bpfman-operator-bundle-ystream-pull-request.yaml
- .tekton/bpfman-operator-bundle-ystream-push.yaml
- .tekton/bpfman-operator-ystream-pull-request.yaml
- .tekton/bpfman-operator-ystream-push.yaml
This PR migrates essential build configuration from the existing ocp-bpfman components to the new ystream components. The bpfman and bpfman-operator applications are being consolidated under a single application called bpfman-ystream.
- Added pathChanged conditions to all ystream Tekton files
- Prevents unnecessary builds when unrelated files change
- Only triggers builds when relevant source files, configuration, or Containerfiles are modified
- Updated .tekton file references to point to ystream variants
- Added build-nudge-files annotations to ystream push pipelines
- Ensures changes to base image files trigger appropriate rebuilds
- Maintains the same rebuild behaviour as existing components
The ystream components should now trigger builds with the same logic as the existing …
> Migrate build configuration from ocp-bpfman to ystream components

- hack/konflux/README.md
Add documentation for managing the transition from legacy ocp-* components to y-stream components in Konflux.
Added new section to `hack/konflux/README.md` documenting:
- Mapping between legacy (ocp-*) and new (y-stream) components
- Instructions for disabling components using Mintmaker annotations
- Specific commands for disabling all legacy components
- Commands for re-enabling components if needed
- Credit to NetObserv team for the documented pattern
This documentation helps track and manage the component transition process as we move to the new y-stream naming convention. It provides clear instructions for:
- Understanding which components are being replaced
- Freezing legacy components to prevent unnecessary builds
- Managing the transition period where both sets of components exist …
> Document Konflux component transition management

- .tekton/bpfman-operator-bundle-ystream-push.yaml
- .tekton/bpfman-operator-ystream-push.yaml
This PR corrects the nudging configuration to properly reflect how our components depend on each other.
After analysing the nudging behaviour and comparing with working examples (NetObserv), we found:
- Bundle had incorrect `build-nudge-files` pointing to component image files it consumes rather than produces
- Operator wasn't rebuilding when agent/daemon images changed (but it needs these for its ConfigMap)
- Bundle was rebuilding for all image changes instead of just operator changes
- Add CEL triggers for `hack/konflux/images/bpfman.txt` and `bpfman-agent.txt`
- When daemon or agent updates, operator rebuilds to update ConfigMap with new image references
- Keeps its own `build-nudge-files: hack/konflux/images/bpfman-operator.txt`
- Remove incorrect `build-nudge-files` annotation …
> tekton: fix nudging configuration for proper component dependencies

- .tekton/bpfman-operator-bundle-ystream-push.yaml
- Add missing `build.appstudio.openshift.io/build-nudge-files` annotation to the bpfman-operator-bundle-ystream push pipeline
- This ensures the bundle digest file (`hack/konflux/images/bpfman-operator-bundle.txt`) gets automatically updated when the bundle is rebuilt
The bpfman-operator-bundle-ystream component builds new images when dependencies change but doesn't update its digest file. The other components (agent and operator) have nudge file annotations that automatically update their digest files, but the bundle was missing this configuration.
> Add missing nudge file annotation for operator bundle

- .tekton/bpfman-operator-bundle-ystream-push.yaml
Configure the bundle Tekton pipeline to use `:latest` tag following the Network Observability Operator's approach, providing stable bundle references for testing and CI workflows.
- Update `bpfman-operator-bundle-ystream-push.yaml` to use `:latest` tag instead of `{{revision}}` 
- Bundle images will now be tagged as `bpfman-operator-bundle-ystream:latest`
- Operator and agent images continue using revision-based tags (unchanged)
The Network Observability Operator team uses `:latest` tags specifically for their bundle images, allowing them to reference `catalog-ystream:latest` in tests without constantly updating digest references. This provides:
- Stable bundle references for CI/testing
- Easier integration workflows
- Consistent approach across OpenShift operators
Following NOO's …
> Configure bundle Tekton pipeline to use :latest tag
